=== Garrafao/phitag/custom/custom-dictionary/custom-dictionary-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This is the xml schema for phitag dictionaries -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="dictionary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="info" type="infoType"/>
                <xs:element name="entries" type="entriesType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="infoType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="entriesType">
        <xs:sequence>
            <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="entryType">
        <xs:sequence>
            <xs:element name="headword" type="xs:string"/>
            <xs:element name="part-of-speech" type="xs:string"/>
            <xs:element name="senses" type="sensesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sensesType">
        <xs:sequence>
            <xs:element name="sense" type="senseType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="senseType">
        <xs:sequence>
            <xs:element name="definition" type="xs:string"/>
            <xs:element name="examples" type="examplesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Garrafao/phitag/custom/custom-dictionary/toy-dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- This is a toy dictionary example for custom xml dict layout -->
<dictionary
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="custom-dictionary-schema.xsd">
    <info>
        <name>Toy Dictionary</name>
        <description>Toy Dictionary</description>
        <author>Toy Dictionary</author>
    </info>

    <entries>
        <entry>
            <headword>Toy</headword>
            <part-of-speech>noun</part-of-speech>
            <senses>
                <sense>
                    <definition>an object for children to play with</definition>
                    <examples>
                        <example>He has a lot of toys.</example>
                        <example>She bought a toy for her son.</example>
                    </examples>
                </sense>
                <sense>
                    <definition>an object for an adult to play with</definition>
                    <examples>
                        <example>He has a lot of toys.</example>
                    </examples>
                </sense>
            </senses>
        </entry>

        <entry>
            <headword>Dictionary</headword>
            <part-of-speech>noun</part-of-speech>
            <senses>
                <sense>
                    <definition>a book that lists the words of a language in alphabetical order and gives their meaning, or that gives the equivalent words in a different language</definition>
                    <examples>
                        <example>an English-Chinese dictionary</example>
                        <example>an English dictionary</example>
                    </examples>
                </sense>
                <sense>
                    <definition>a book that explains the words that are used in a particular subject</definition>
                    <examples>
                        <example>a dictionary of biology</example>
                        <example>a dictionary of slang</example>
                    </examples>
                </sense>
            </senses>
        </entry>
    </entries>
</dictionary>
